### ISSUE TITLE
Module description formatting can result in invalid URLs and spurious characters

### ISSUE THREAD

**Issue by wlupton** [YangCatalog/yangcatalog-ui#5] opened 2021-07-14 08:37 UTC
I noticed a problem with the formatting of the module description.

For example, go to <https://yangcatalog.org/yang-search/module_details/bbf-fast@2020-10-13> and expand the schema to find this in the top-level description (note the IPR Policy URL):

```
The above license is used as a license under copyright only.
     Please reference the Forum IPR Policy for patent licensing terms
     <https://www.broadband-forum.org/ipr-policy>.
```

Now go back and expand the description to see this:

```
The above license is used as a license under copyright only.
Please reference the Forum IPR Policy for patent licensing terms
<https://www.broadband-forum.org/ipr-policy>;.
```

Note that the link is to <https://www.broadband-forum.org/ipr-policy%3E> (it includes the ">" character and so is invalid) and there's a spurious additional rendered ";" character.

**Comment by SlavomirMazurPantheon** [comment] 2021-07-14 09:58
Hello,

bug fixed by commit https://github.com/YangCatalog/yangcatalog-ui/commit/94bcb9a4417f71c34f57a72108d440456e880854.
Changes should also be visible in yangcatalog.org, feel free to test if everything works fine.
**INFO:** Problem caused by replacing < > characters by their HTML alternatives. Also fixed for mailto: hrefs.

Regards,
Slavomir Mazur

**Comment by SlavomirMazurPantheon** [comment] 2021-07-14 11:23
Duplicate of #4

**Closed by SlavomirMazurPantheon** 2021-07-14 11:23 UTC
Labels: bug
